import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CalendarDays, Menu, Ticket, Truck, X } from "lucide-react";
import sponsors from "../data/legacy-sponsors.json";

type TruckCard = { truckNumber: string; companyName: string; brand: string; model: string; city: string; category: string; imageUrl?: string | null; profileUrl?: string };

const event = { year: 2027, date: "2-3 juli 2027", slug: "aseda-truckmeet-2027", pretix: import.meta.env.VITE_PRETIX_EVENT_URL ?? "https://pretix.example.com/truckmeet/2027/" };
const tiers = ["Huvudpartner", "Platinapartner", "Guldpartner", "Silverpartner", "Bronspartner"];
const fallbackTrucks: TruckCard[] = ["Scania 770S V8", "Volvo FH16 750", "Mercedes-Benz Actros L", "MAN TGX 18.640", "DAF XG+", "Iveco S-Way"].map((model, index) => ({ truckNumber: `B${String(127 + index).padStart(3, "0")}`, companyName: `DEMO ${["Johanssons Åkeri", "Smålands Transport", "Växjö Logistik", "Kronobergs Åkeri", "Sydkust Frakt", "Åseda Transport"][index]}`, brand: model.split(" ")[0], model, city: ["Kalmar", "Åseda", "Växjö", "Vetlanda", "Oskarshamn", "Hultsfred"][index], category: index % 2 ? "showtruck" : "dragbil", imageUrl: "https://asedatruckmeet.se/web/image/3834-8ed0e93c/A7400342.webp" }));

function navigate(path: string) { window.history.pushState({}, "", path); window.dispatchEvent(new PopStateEvent("popstate")); window.scrollTo({ top: 0, behavior: "instant" }); }

function Logo() { return <a className="brand" href="/" onClick={(event) => { event.preventDefault(); navigate("/"); }}><span className="brand-logo"><img src="/aseda-truckmeet-logo.png" alt="Åseda Truckmeet" /></span><span><strong>ÅSEDA TRUCKMEET</strong><small>SMÅLAND · 2027</small></span></a>; }

function Shell({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false);
  const links = [["Eventet", "/"], ["Biljetter", "/biljetter"], ["Lastbilar", "/lastbilar"], ["Partners", "/partners"], ["Besök", "/besok"]];
  return <><header className="site-header"><Logo /><nav className={open ? "nav is-open" : "nav"}>{links.map(([label, path]) => <a href={path} key={path} onClick={(event) => { event.preventDefault(); setOpen(false); navigate(path); }}>{label}</a>)}</nav><div className="header-actions"><a className="ticket-button" href="/biljetter" onClick={(event) => { event.preventDefault(); navigate("/biljetter"); }}><Ticket size={16} /> Biljetter</a><button className="menu-button" aria-label={open ? "Stäng meny" : "Öppna meny"} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div></header>{children}<footer className="site-footer"><div><Logo /><p>Småland. Lastbilar. Folkfest.</p></div><div><strong>ÅSEDA TRUCKMEET 2027</strong><span>{event.date}</span><span>Åseda Folkets Park</span></div><div><strong>SNABBT</strong><a href="/biljetter" onClick={(e) => { e.preventDefault(); navigate("/biljetter"); }}>Biljetter</a><a href="/lastbilar" onClick={(e) => { e.preventDefault(); navigate("/lastbilar"); }}>Lastbilar</a><a href="/partners" onClick={(e) => { e.preventDefault(); navigate("/partners"); }}>Partners</a></div></footer></>;
}

function Home() { return <><section className="hero"><div className="hero-image"><img src="https://asedatruckmeet.se/web/image/3834-8ed0e93c/A7400342.webp" alt="Lastbil på Åseda Truckmeet" /></div><div className="hero-content"><img className="hero-logo" src="/aseda-truckmeet-logo.png" alt="Åseda Truckmeet" /><p className="eyebrow">{event.date} · Åseda Folkets Park</p><h1>Småland.<br /><em>Lastbilar.</em><br />Folkfest.</h1><p className="hero-lead">Showtrucks, krom, fordonsljus, musik och gemenskap. Sveriges råaste truckhelg är tillbaka.</p><div className="actions"><a className="button primary" href="/biljetter" onClick={(e) => { e.preventDefault(); navigate("/biljetter"); }}>Köp biljett <ArrowRight size={18} /></a><a className="button secondary" href="/lastbilar" onClick={(e) => { e.preventDefault(); navigate("/lastbilar"); }}>Anmäl lastbil</a></div></div><div className="hero-stamp"><CalendarDays size={18} /><strong>2—3</strong><span>JULI 2027</span></div></section><section className="stats"><div><strong>187</strong><span>Anmälda lastbilar</span></div><div><strong>2</strong><span>Dagar av truckkultur</span></div><div><strong>5</strong><span>Sponsornivåer</span></div><div><strong>100%</strong><span>Småländsk folkfest</span></div></section><SponsorRunway /><section className="intro"><p className="eyebrow">Åseda Truckmeet 2027</p><h2>Det börjar med en lastbil.<br /><em>Det slutar i gemenskap.</em></h2><p>En helg för förare, åkerier, entusiaster, familjer och alla som älskar ljudet av diesel och blänket i krom.</p><a className="text-link" href="/partners" onClick={(e) => { e.preventDefault(); navigate("/partners"); }}>Möt våra partners <ArrowRight size={16} /></a></section></>; }

function SponsorRunway() { return <section className="sponsors"><div className="section-head"><div><p className="eyebrow">Med på resan</p><h2>Våra partners</h2></div><a className="text-link" href="/partners" onClick={(e) => { e.preventDefault(); navigate("/partners"); }}>Alla partners <ArrowRight size={16} /></a></div>{tiers.map((tier) => { const items = sponsors.sponsors.filter((sponsor) => sponsor.tier === tier); if (!items.length) return null; const loop = tier === "Guldpartner" || tier === "Silverpartner" || tier === "Bronspartner"; return <div className={`sponsor-row ${loop ? "is-moving" : ""}`} key={tier}><span className="tier-label">{tier}</span><div className="sponsor-track">{[...items, ...(loop ? items : [])].map((sponsor, index) => <a className="sponsor-chip" href={sponsor.websiteUrl ?? "#"} target="_blank" rel="noreferrer" key={`${sponsor.slug}-${index}`}><img src={sponsor.logoPath} alt="" /><strong>{sponsor.name}</strong></a>)}</div></div>; })}</section>; }

function PageHeader({ eyebrow, title, lead }: { eyebrow: string; title: string; lead: string }) { return <section className="page-header"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{lead}</p></section>; }

function Tickets() { return <><PageHeader eyebrow="Åseda Truckmeet · 2027" title="Biljetter" lead="Välj din biljett och fortsätt till den säkra Pretix-checkouten." /><section className="ticket-grid">{[{ title: "Helgpass", text: "Entré till hela Truckmeet-helgen.", price: "495 kr" }, { title: "Lördagsbiljett", text: "En full dag med showtrucks, krom och folkfest.", price: "295 kr" }, { title: "Utställningslastbil", text: "Anmäl din lastbil till årets Truckmeet.", price: "350 kr" }].map((ticket) => <article key={ticket.title}><span className="ticket-kicker">BILJETT</span><h2>{ticket.title}</h2><p>{ticket.text}</p><div><strong>{ticket.price}</strong><a className="button primary" href={event.pretix}>Välj <ArrowRight size={16} /></a></div></article>)}</section><section className="checkout"><p className="eyebrow">Säker checkout</p><h2>Slutför köpet i Pretix</h2><p>Betalning, order, QR-biljett och återbetalning hanteras av Pretix.</p><a className="button primary" href={event.pretix}>Öppna biljettköpet <ArrowRight size={18} /></a></section></>; }

function Trucks() { const [trucks, setTrucks] = useState<TruckCard[]>(fallbackTrucks); const [search, setSearch] = useState(""); useEffect(() => { const base = import.meta.env.VITE_PUBLIC_API_BASE_URL; if (!base) return; fetch(`${base.replace(/\/$/, "")}/api/public/events/${event.slug}/trucks?limit=100`).then((response) => response.ok ? response.json() : null).then((data) => { if (data?.trucks?.length) setTrucks(data.trucks); }).catch(() => undefined); }, []); const filtered = useMemo(() => trucks.filter((truck) => `${truck.companyName} ${truck.brand} ${truck.model} ${truck.city} ${truck.truckNumber}`.toLowerCase().includes(search.toLowerCase())), [trucks, search]); return <><PageHeader eyebrow="Publika lastbilar" title="Truckgalleriet" lead="Möt ekipagen, åkerierna och människorna bakom årets show." /><div className="search"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Sök åkeri, modell, ort eller trucknummer" /><span>{filtered.length} lastbilar</span></div><section className="truck-grid">{filtered.map((truck) => <article className="truck-card" key={truck.truckNumber}><img src={truck.imageUrl ?? fallbackTrucks[0].imageUrl} alt={`${truck.companyName} ${truck.brand} ${truck.model}`} /><div><span>{truck.truckNumber}</span><h2>{truck.companyName}</h2><p>{truck.brand} {truck.model} · {truck.city}</p><a className="text-link" href={truck.profileUrl ?? `#${truck.truckNumber}`}>Se truckprofil <ArrowRight size={16} /></a></div></article>)}</section></>; }

function Partners() { return <><PageHeader eyebrow="Med på resan" title="Partners" lead="Företagen som gör Åseda Truckmeet möjligt." /><section className="partner-levels">{tiers.map((tier) => { const items = sponsors.sponsors.filter((sponsor) => sponsor.tier === tier); return <section key={tier}><div className="section-head"><h2>{tier}</h2><span>{items.length} partners</span></div><div className="partner-grid">{items.map((sponsor) => <a href={sponsor.websiteUrl ?? "#"} target="_blank" rel="noreferrer" key={sponsor.slug}><img src={sponsor.logoPath} alt={sponsor.name} /><strong>{sponsor.name}</strong><p>{sponsor.description}</p></a>)}</div></section>; })}</section></>; }

function SimplePage({ title, eyebrow, lead }: { title: string; eyebrow: string; lead: string }) { return <><PageHeader eyebrow={eyebrow} title={title} lead={lead} /><section className="info-panel"><Truck size={26} /><h2>Mer innehåll på väg</h2><p>Den här sektionen kopplas till Supabase och administrationsgränssnittet i nästa lager. Frontendens publika struktur är redan klar för appen.</p></section></>; }

export function App() { const [path, setPath] = useState(window.location.pathname); useEffect(() => { const listener = () => setPath(window.location.pathname); window.addEventListener("popstate", listener); return () => window.removeEventListener("popstate", listener); }, []); let page: React.ReactNode = <Home />; if (path.startsWith("/biljetter")) page = <Tickets />; else if (path.startsWith("/lastbilar")) page = <Trucks />; else if (path.startsWith("/partners")) page = <Partners />; else if (path.startsWith("/besok")) page = <SimplePage eyebrow="Planera besöket" title="Besöksinfo" lead="Allt du behöver veta inför Truckmeet i Åseda." />; else if (path.startsWith("/admin")) page = <SimplePage eyebrow="Control" title="Admin" lead="Admin körs bakom ett separat Supabase Edge Function-lager." />; return <Shell><main>{page}</main></Shell>; }
